admin:
  port: 9990

routers:
- protocol: http
  baseDtab: /http => /$/inet/127.1/9990;
  servers:
  - port: 8080

- protocol: thrift
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
  servers:
  - port: 8081
    ip: 0.0.0.0
    thriftFramed: false
  client:
    thriftFramed: false
  thriftMethodInDst: true
