admin:
  port: 9991

namers: []
storage:
  kind: io.l5d.inMemory
  namespaces:
    default: |
      /host             => /$/inet/graphql/3000;
      /host/numbers     => /$/inet/numbers/9090;
      /host/calculator  => /$/inet/calculator/9091;
      /http/1.1/*       => /host;
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
